id: P010622
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:16:55.676473
source_metadata:
  id: bdr:W1KG15593
  title: དམ་པའི་ཆོས་མངོན་པ་མཛོད་ཀྱི་ཚིག་ལེའུར་བྱས་པའི་འགྲེལ་པ་མངོན་པའི་རྒྱན།
  author: ''
  volumes:
    ee174f63b3194cae83e3cfcb69e41b08:
      image_group_id: I1KG15595
      title: ''
      volume_number: 1
      total_pages: 718
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
